export class Videogame {
  constructor(
    public id?: number,
    public title?: string,
    public features_handheld?: boolean,
    public features_maxplayers?: number,
    public features_multiplatform?: boolean,
    public features_online?: boolean,
    public metadata_genres?: string,
    public metadata_licensed?: boolean,
    public metadata_publishers?: string,
    public metadata_sequel?: boolean,
    public metrics_reviewscore?: number,
    public metrics_sales?: number,
    public metrics_usedprice?: number,
    public release_console?: string,
    public release_rating?: string,
    public release_rerelease?: boolean,
    public release_year?: number,
    public length_allplaystyles_average?: number,
    public length_allplaystyles_leisure?: number,
    public length_allplaystyles_median?: number,
    public length_allplaystyles_polled?: number,
    public length_allplaystyles_rushed?: number,
    public length_completionists_average?: number,
    public length_completionists_leisure?: number,
    public length_completionists_median?: number,
    public length_compltetionists_polled?: number,
    public length_completionists_rushed?: number,
    public length_mainplusextras_average?: number,
    public length_mainplusextras_leisure?: number,
    public length_mainplusextras_median?: number,
    public length_mainplusextras_polled?: number,
    public length_mainplusextras_rushed?: number,
    public length_mainstory_average?: number,
    public length_mainstory_leisure?: number,
    public length_mainstory_median?: number,
    public length_mainstory_polled?: number,
    public length_mainstory_rushed?: number
  ){}
}
